name: Aula 03

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'minha variavel'

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
       
    - name: ${{ env. WORKFLOW_VAR }}
      uses: actions/upload-artifact@v2.2.3
    
