name: Aula 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'variavel de ambiente'
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    
      - name: Checkout
        run: action/checkout@v2.3.4
        
      - name: Upload
        run: action/upload-artifact@v2.2.3
