name: Aula3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'minha variavel no escopo do workflow'

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.4
     
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{ env.WORKFLOW_VAR }}
        path: .
        if-no-files-found: error
        retention-days: 3
